package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.bouncycastle.util.encoders.Base64;
import org.jpos.ee.User;

import id.co.keriss.consolidate.DS.DigiSign;

/**
 * Card generated by hbm2java
 */
public class Interface_Mitra implements java.io.Serializable {

	private long id;
	private Mitra mitra;
	private String i_aktivasi;
	private String i_sign_doc;
	private String token_auth;
	
	public Interface_Mitra() {
		
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Mitra getMitra() {
		return mitra;
	}

	public void setMitra(Mitra mitra) {
		this.mitra = mitra;
	}

	public String getI_aktivasi() {
		return i_aktivasi;
	}

	public void setI_aktivasi(String i_aktivasi) {
		this.i_aktivasi = i_aktivasi;
	}

	public String getI_sign_doc() {
		return i_sign_doc;
	}

	public void setI_sign_doc(String i_sign_doc) {
		this.i_sign_doc = i_sign_doc;
	}

	public String getToken_auth() {
		return token_auth;
	}

	public void setToken_auth(String token_auth) {
		this.token_auth = token_auth;
	}	
	

}
