package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Batch generated by hbm2java
 */
public class Batch  implements java.io.Serializable {


     private Long id;
     private int number;
     private Long amount;
     private boolean settled;
     private Date settledate;
     private Terminal terminal;
     private Set transaction = new HashSet(0);

    public Batch() {
    }

    public Batch(int number, Long amount, boolean settled, Date settledate, Terminal terminal, Set transaction) {
       this.number = number;
       this.amount = amount;
       this.settled = settled;
       this.settledate = settledate;
       this.terminal = terminal;
       this.transaction = transaction;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public Long getAmount() {
        return this.amount;
    }
    
    public void setAmount(Long amount) {
        this.amount = amount;
    }
    public boolean isSettled() {
        return this.settled;
    }
    
    public void setSettled(boolean settled) {
        this.settled = settled;
    }
    public Date getSettledate() {
        return this.settledate;
    }
    
    public void setSettledate(Date settledate) {
        this.settledate = settledate;
    }
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }
    public Set getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Set transaction) {
        this.transaction = transaction;
    }




}


