package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Merchant generated by hbm2java
 */
public class RegistrationLog  implements java.io.Serializable {


     private long id;
     private String email;
     private String no_identitas;
     private String nama;
     private char jk = 'X';
     private String tempat_lahir;
     private Date tgl_lahir;
     private String alamat;
     private String kelurahan;
     private String kecamatan;
     private String kota;
     private String propinsi;
     private String kodepos;
     private String no_handphone;
     private String npwp;
     private String imageKTP;
     private String imageNPWP;
     private String imageWajah;
     private String imageTtd;
     private Mitra mitra;
     private Boolean data_exists=false;
     private Boolean verifikasi=true;
     private Boolean redirect=false;
     private String imageWajahDukcapil;
     private String imageWefie;
     private String kode_bank;
     private String no_rekening;
     private String message_req;
     private String message_response;
     private String username;
     private char type = '1';
     private String imageKitas;
     private String email_perusahaan;
     private String i_buku_tabungan;
    
     
     
     
     

	public String getI_buku_tabungan() {
		return i_buku_tabungan;
	}

	public void setI_buku_tabungan(String i_buku_tabungan) {
		this.i_buku_tabungan = i_buku_tabungan;
	}

	public char getJk() {
		return jk;
	}

	public void setJk(char jk) {
		this.jk = jk;
	}


	public char getType() {
		return type;
	}

	public void setType(char type) {
		this.type = type;
	}

	public String getMessage_req() {
		return message_req;
	}

	public void setMessage_req(String message_req) {
		this.message_req = message_req;
	}

	public String getMessage_response() {
		return message_response;
	}

	public void setMessage_response(String message_response) {
		this.message_response = message_response;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}


	

	public String getImageKitas() {
		return imageKitas;
	}

	public void setImageKitas(String imageKitas) {
		this.imageKitas = imageKitas;
	}

	public String getEmail_perusahaan() {
		return email_perusahaan;
	}

	public void setEmail_perusahaan(String email_perusahaan) {
		this.email_perusahaan = email_perusahaan;
	}

	public String getImageWefie() {
		return imageWefie;
	}

	public void setImageWefie(String imageWefie) {
		this.imageWefie = imageWefie;
	}

	public String getImageWajahDukcapil() {
		return imageWajahDukcapil;
	}

	public void setImageWajahDukcapil(String imageWajahDukcapil) {
		this.imageWajahDukcapil = imageWajahDukcapil;
	}

	public Boolean getRedirect() {
		return redirect;
	}

	public void setRedirect(Boolean redirect) {
		this.redirect = redirect;
	}

	public Boolean getData_exists() {
		return data_exists;
	}

	public Boolean getVerifikasi() {
		return verifikasi;
	}

	public void setVerifikasi(Boolean verifikasi) {
		this.verifikasi = verifikasi;
	}
//
//	public RegistrationLog() {
//		
//	}
	
	public String getImageKTP() {
		return imageKTP;
	}

	public void setImageKTP(String imageKTP) {
		this.imageKTP = imageKTP;
	}

	public String getImageNPWP() {
		return imageNPWP;
	}

	public void setImageNPWP(String imageNPWP) {
		this.imageNPWP = imageNPWP;
	}

	public String getImageWajah() {
		return imageWajah;
	}

	public void setImageWajah(String imageWajah) {
		this.imageWajah = imageWajah;
	}

	public String getImageTtd() {
		return imageTtd;
	}

	public void setImageTtd(String imageTtd) {
		this.imageTtd = imageTtd;
	}

	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getNama() {
		return nama;
	}
	public void setNama(String nama) {
		this.nama = nama;
	}
	
	public String getNo_identitas() {
		return no_identitas;
	}
	public void setNo_identitas(String no_identitas) {
		this.no_identitas = no_identitas.trim();
	}
	
	public String getTempat_lahir() {
		return tempat_lahir;
	}
	public void setTempat_lahir(String tempat_lahir) {
		this.tempat_lahir = tempat_lahir;
	}
	public Date getTgl_lahir() {
		return tgl_lahir;
	}
	public void setTgl_lahir(Date tgl_lahir) {
		this.tgl_lahir = tgl_lahir;
	}
	public String getAlamat() {
		return alamat;
	}
	public void setAlamat(String alamat) {
		this.alamat = alamat;
	}
	public String getKelurahan() {
		return kelurahan;
	}
	public void setKelurahan(String kelurahan) {
		this.kelurahan = kelurahan;
	}
	public String getKecamatan() {
		return kecamatan;
	}
	public void setKecamatan(String kecamatan) {
		this.kecamatan = kecamatan;
	}
	public String getKota() {
		return kota;
	}
	public void setKota(String kota) {
		this.kota = kota;
	}
	public String getPropinsi() {
		return propinsi;
	}
	public void setPropinsi(String propinsi) {
		this.propinsi = propinsi;
	}
	public String getKodepos() {
		return kodepos;
	}
	public void setKodepos(String kodepos) {
		this.kodepos = kodepos;
	}
	public String getNo_handphone() {
		return no_handphone;
	}
	public void setNo_handphone(String no_handphone) {
		this.no_handphone = no_handphone;
	}
	public String getNpwp() {
		return npwp;
	}
	public void setNpwp(String npwp) {
		this.npwp = npwp;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email.toLowerCase().trim();
	}
	public Mitra getMitra() {
		return mitra;
	}
	public void setMitra(Mitra mitra) {
		this.mitra = mitra;
	}

	public Boolean isData_exists() {
		return data_exists;
	}

	public void setData_exists(Boolean data_exists) {
		this.data_exists = data_exists;
	}

	public String getKode_bank() {
		return kode_bank;
	}

	public void setKode_bank(String kode_bank) {
		this.kode_bank = kode_bank;
	}

	public String getNo_rekening() {
		return no_rekening;
	}

	public void setNo_rekening(String no_rekening) {
		this.no_rekening = no_rekening;
	}
        
}